// ============================================================
// 2A AGENCY | SYSTEM OF RECORD - DATABASE
// CATEGORY: 08_MOBILITY (TOP 100 AI IQ INDEX)
// ============================================================

const mobilityData = [
    { id: "BUG", name: "Bugatti", score: 99, doc_label: "BUG_INTEGRITY_2025", doc_hash: "", hash: "" },
    { id: "RR_MOT", name: "Rolls-Royce Motor Cars", score: 99, doc_label: "RR_SPECTRE_ESG_2025", doc_hash: "", hash: "" },
    { id: "RACE", name: "Ferrari", score: 98, doc_label: "FERRARI_ANNUAL_REPORT_2025", doc_hash: "", hash: "" },
    { id: "KOEN", name: "Koenigsegg", score: 98, doc_label: "KOENIGSEGG_TECH_MANIFESTO", doc_hash: "", hash: "" },
    { id: "PAG", name: "Pagani", score: 98, doc_label: "PAGANI_SENTINEL_AUDIT", doc_hash: "", hash: "" },
    { id: "LMT", name: "Lockheed Martin", score: 98, doc_label: "LMT_GLOBAL_IMPACT_2025", doc_hash: "", hash: "" },
    { id: "RR_ENG", name: "Rolls-Royce Holdings", score: 98, doc_label: "RR_AERO_NON_FINANCIAL", doc_hash: "", hash: "" },
    { id: "RIM", name: "Rimac", score: 97, doc_label: "RIMAC_NEVERA_DATA_2025", doc_hash: "", hash: "" },
    { id: "POR", name: "Porsche", score: 97, doc_label: "PORSCHE_SUSTAINABILITY_2025", doc_hash: "", hash: "" },
    { id: "AIR", name: "Airbus", score: 97, doc_label: "AIRBUS_UNIVERSAL_REGISTRATION_2025", doc_hash: "", hash: "" },
    { id: "DAS", name: "Dassault Aviation", score: 97, doc_label: "DAS_ANNUAL_FINANCIAL_2025", doc_hash: "", hash: "" },
    { id: "NOC", name: "Northrop Grumman", score: 97, doc_label: "NOC_ESG_REPORT_2025", doc_hash: "", hash: "" },
    { id: "BENT", name: "Bentley", score: 97, doc_label: "BENTLEY_BEYOND100_REPORT", doc_hash: "", hash: "" },
    { id: "MBG", name: "Mercedes-Benz", score: 96, doc_label: "MB_SUSTAINABILITY_REPORT_2025", doc_hash: "", hash: "" },
    { id: "GULF", name: "Gulfstream", score: 96, doc_label: "GULF_SUSTAINABILITY_PROG", doc_hash: "", hash: "" },
    { id: "LAMB", name: "Lamborghini", score: 96, doc_label: "LAMBO_DIREZIONE_COR_TAURI", doc_hash: "", hash: "" },
    { id: "BMW", name: "BMW", score: 95, doc_label: "BMW_GROUP_REPORT_2025", doc_hash: "", hash: "" },
    { id: "VOLV", name: "Volvo", score: 95, doc_label: "VOLVO_ANNUAL_SUSTAINABILITY", doc_hash: "", hash: "" },
    { id: "WAY", name: "Waymo", score: 95, doc_label: "WAYMO_SAFETY_PERFORMANCE_DATA", doc_hash: "", hash: "" },
    { id: "LEX", name: "Lexus", score: 95, doc_label: "TOYOTA_LEXUS_ESG_2025", doc_hash: "", hash: "" },
    { id: "MAERSK", name: "Maersk", score: 95, doc_label: "MAERSK_SUSTAINABILITY_2025", doc_hash: "", hash: "" },
    { id: "SCANIA", name: "Scania", score: 95, doc_label: "SCANIA_ANNUAL_REPORT", doc_hash: "", hash: "" },
    { id: "TSLA", name: "Tesla", score: 94, doc_label: "TESLA_IMPACT_REPORT_2025", doc_hash: "", hash: "" },
    { id: "AUDI", name: "Audi", score: 94, doc_label: "AUDI_VOT_PROGRESS_2025", doc_hash: "", hash: "" },
    { id: "MCL", name: "McLaren", score: 94, doc_label: "MCLAREN_SUSTAINABILITY", doc_hash: "", hash: "" },
    { id: "ALP", name: "Alpine", score: 93, doc_label: "RENAULT_ALPINE_INTEGRITY", doc_hash: "", hash: "" },
    { id: "TOY", name: "Toyota", score: 93, doc_label: "TOYOTA_ESG_2025", doc_hash: "", hash: "" },
    { id: "DHL", name: "DHL", score: 93, doc_label: "DPDHL_ESG_STATEMENTS_2025", doc_hash: "", hash: "" },
    { id: "UBER", name: "Uber", score: 93, doc_label: "UBER_ESG_REPORT_2025", doc_hash: "", hash: "" },
    { id: "POLE", name: "Polestar", score: 93, doc_label: "POLESTAR_LCA_REPORT", doc_hash: "", hash: "" },
    { id: "MAN", name: "MAN", score: 93, doc_label: "MAN_TRUCK_BUS_ESG", doc_hash: "", hash: "" },
    { id: "UPS", name: "UPS", score: 92, doc_label: "UPS_SUSTAINABILITY_2025", doc_hash: "", hash: "" },
    { id: "CMA", name: "CMA CGM", score: 92, doc_label: "CMA_SUSTAINABILITY_REPORT", doc_hash: "", hash: "" },
    { id: "BYD", name: "BYD", score: 92, doc_label: "BYD_SOCIAL_RESPONSIBILITY", doc_hash: "", hash: "" },
    { id: "LR", name: "Land Rover", score: 92, doc_label: "JLR_ANNUAL_REPORT", doc_hash: "", hash: "" },
    { id: "GEN", name: "Genesis", score: 92, doc_label: "HYUNDAI_GENESIS_ESG", doc_hash: "", hash: "" },
    { id: "TRI", name: "Triumph", score: 92, doc_label: "TRIUMPH_SUSTAINABILITY", doc_hash: "", hash: "" },
    { id: "SEA_D", name: "Sea-Doo", score: 92, doc_label: "BRP_SEA_DOO_INTEGRITY", doc_hash: "", hash: "" },
    { id: "SIX", name: "Sixt", score: 92, doc_label: "SIXT_ESG_REPORT", doc_hash: "", hash: "" },
    { id: "NIO", name: "Nio", score: 92, doc_label: "NIO_USER_REPORT_2025", doc_hash: "", hash: "" },
    { id: "RIVN", name: "Rivian", score: 91, doc_label: "RIVIAN_IMPACT_REPORT_2025", doc_hash: "", hash: "" },
    { id: "FEDEX", name: "FedEx", score: 91, doc_label: "FEDEX_ESG_REPORT_2025", doc_hash: "", hash: "" },
    { id: "BLA", name: "BlaBlaCar", score: 91, doc_label: "BLABLACAR_IMPACT_2025", doc_hash: "", hash: "" },
    { id: "BOM", name: "Bombardier", score: 91, doc_label: "BOM_ESG_2025", doc_hash: "", hash: "" },
    { id: "ASTON", name: "Aston Martin", score: 91, doc_label: "ASTON_RACING_GREEN", doc_hash: "", hash: "" },
    { id: "MINI", name: "Mini", score: 91, doc_label: "BMW_MINI_ESG", doc_hash: "", hash: "" },
    { id: "BRRP", name: "BRP", score: 91, doc_label: "BRP_ANNUAL_REPORT", doc_hash: "", hash: "" },
    { id: "YAM", name: "Yamaha", score: 91, doc_label: "YAMAHA_SUSTAINABILITY", doc_hash: "", hash: "" },
    { id: "HAPAG", name: "Hapag-Lloyd", score: 91, doc_label: "HAPAG_ESG_DATA", doc_hash: "", hash: "" },
    { id: "HYU", name: "Hyundai", score: 91, doc_label: "HYUNDAI_ESG_PROGRESS", doc_hash: "", hash: "" },
    { id: "X_PENG", name: "XPeng", score: 91, doc_label: "XPENG_TECH_REPORT", doc_hash: "", hash: "" },
    { id: "LCID", name: "Lucid Motors", score: 90, doc_label: "LUCID_ESG_2025", doc_hash: "", hash: "" },
    { id: "KIA", name: "Kia", score: 90, doc_label: "KIA_SUSTAINABILITY", doc_hash: "", hash: "" },
    { id: "ALFA", name: "Alfa Romeo", score: 90, doc_label: "ALFA_INTEGRITY_INDEX", doc_hash: "", hash: "" },
    { id: "LI", name: "Li Auto", score: 90, doc_label: "LI_AUTO_ESG", doc_hash: "", hash: "" },
    { id: "SUB", name: "Subaru", score: 90, doc_label: "SUBARU_ESG_DATA", doc_hash: "", hash: "" },
    { id: "MSC", name: "MSC", score: 90, doc_label: "MSC_MARITIME_REPORT", doc_hash: "", hash: "" },
    { id: "HARL", name: "Harley-Davidson", score: 90, doc_label: "HD_SUSTAINABILITY", doc_hash: "", hash: "" },
    { id: "KTM", name: "KTM", score: 90, doc_label: "KTM_PIERER_ESG", doc_hash: "", hash: "" },
    { id: "POLA", name: "Polaris", score: 90, doc_label: "POLARIS_ESG_REPORT", doc_hash: "", hash: "" },
    { id: "CAN_AM", name: "Can-Am", score: 90, doc_label: "BRP_CANAM_INTEGRITY", doc_hash: "", hash: "" },
    { id: "DAF", name: "DAF", score: 90, doc_label: "DAF_TRUCKS_ESG", doc_hash: "", hash: "" },
    { id: "VOW", name: "Volkswagen", score: 89, doc_label: "VW_GROUP_ESG_2025", doc_hash: "", hash: "" },
    { id: "JAG", name: "Jaguar", score: 89, doc_label: "JLR_JAGUAR_REIMAGINE", doc_hash: "", hash: "" },
    { id: "LOT", name: "Lotus", score: 89, doc_label: "LOTUS_DRIVING_GREEN", doc_hash: "", hash: "" },
    { id: "ENT", name: "Enterprise", score: 89, doc_label: "ENTERPRISE_ESG_INDEX", doc_hash: "", hash: "" },
    { id: "LYFT", name: "Lyft", score: 89, doc_label: "LYFT_IMPACT_REPORT", doc_hash: "", hash: "" },
    { id: "MAS", name: "Maserati", score: 89, doc_label: "STELLANTIS_MASERATI_ESG", doc_hash: "", hash: "" },
    { id: "MAZ", name: "Mazda", score: 89, doc_label: "MAZDA_SUSTAINABILITY_REPORT", doc_hash: "", hash: "" },
    { id: "ACU", name: "Acura", score: 89, doc_label: "HONDA_ACURA_ESG", doc_hash: "", hash: "" },
    { id: "JOBY", name: "Joby Aviation", score: 89, doc_label: "JOBY_SEC_FILING_2025", doc_hash: "", hash: "" },
    { id: "COW", name: "Cowboy", score: 89, doc_label: "COWBOY_SENTINEL_AUDIT", doc_hash: "", hash: "" },
    { id: "F", name: "Ford", score: 88, doc_label: "FORD_INTEGRITY_2025", doc_hash: "", hash: "" },
    { id: "ARCH", name: "Archer Aviation", score: 88, doc_label: "ARCHER_ESG_PROGRESS", doc_hash: "", hash: "" },
    { id: "PEU", name: "Peugeot", score: 88, doc_label: "STELLANTIS_PEUGEOT_ESG", doc_hash: "", hash: "" },
    { id: "JEEP", name: "Jeep", score: 88, doc_label: "STELLANTIS_JEEP_ESG", doc_hash: "", hash: "" },
    { id: "LIVEW", name: "LiveWire", score: 88, doc_label: "HD_LIVEWIRE_REPORT", doc_hash: "", hash: "" },
    { id: "SMART", name: "Smart", score: 88, doc_label: "GEELY_SMART_ESG", doc_hash: "", hash: "" },
    { id: "IVECO", name: "Iveco", score: 88, doc_label: "IVECO_GROUP_SUSTAINABILITY", doc_hash: "", hash: "" },
    { id: "GM", name: "General Motors", score: 87, doc_label: "GM_SUSTAINABILITY_2025", doc_hash: "", hash: "" },
    { id: "VOLO", name: "Volocopter", score: 87, doc_label: "VOLO_ESG_INDEX", doc_hash: "", hash: "" },
    { id: "REN", name: "Renault", score: 87, doc_label: "RENAULT_ESG_REPORT", doc_hash: "", hash: "" },
    { id: "DS", name: "DS Automobiles", score: 87, doc_label: "STELLANTIS_DS_ESG", doc_hash: "", hash: "" },
    { id: "ANG", name: "Angell", score: 87, doc_label: "ANGELL_MOBILITY_DATA", doc_hash: "", hash: "" },
    { id: "NIS", name: "Nissan", score: 86, doc_label: "NISSAN_GREEN_PROG", doc_hash: "", hash: "" },
    { id: "CRU", name: "Cruise", score: 86, doc_label: "GM_CRUISE_SAFETY", doc_hash: "", hash: "" },
    { id: "NAVISTAR", name: "Navistar", score: 86, doc_label: "NAVISTAR_ESG_DATA", doc_hash: "", hash: "" },
    { id: "LIL", name: "Lilium", score: 85, doc_label: "LILIUM_ESG_REPORT", doc_hash: "", hash: "" },
    { id: "CIT", name: "Citroën", score: 85, doc_label: "STELLANTIS_CITROEN_ESG", doc_hash: "", hash: "" },
    { id: "ST_LINE", name: "Starline", score: 85, doc_label: "SENTINEL_INDEX", doc_hash: "", hash: "" },
    { id: "ZOOX", name: "Zoox", score: 85, doc_label: "AMZN_ZOOX_SAFETY", doc_hash: "", hash: "" },
    { id: "STLA", name: "Stellantis", score: 84, doc_label: "STELLANTIS_CSR_REPORT", doc_hash: "", hash: "" },
    { id: "INF", name: "Infiniti", score: 84, doc_label: "NISSAN_INFINITI_ESG", doc_hash: "", hash: "" },
    { id: "CAK", name: "CAKE", score: 84, doc_label: "CAKE_ESG_AUDIT", doc_hash: "", hash: "" },
    { id: "FIAT", name: "Fiat", score: 82, doc_label: "STELLANTIS_FIAT_ESG", doc_hash: "", hash: "" },
    { id: "HERTZ", name: "Hertz", score: 82, doc_label: "HERTZ_ESG_INDEX", doc_hash: "", hash: "" },
    { id: "BA", name: "Boeing", score: 82, doc_label: "BOEING_SAFETY_ACTION_PLAN", doc_hash: "", hash: "" },
    { id: "NAV", name: "Navya", score: 78, doc_label: "NAVYA_ESG_DATA", doc_hash: "", hash: "" },
    { id: "VANM", name: "VanMoof", score: 65, doc_label: "RECOVERY_DOCS_2025", doc_hash: "", hash: "" },
    { id: "LUCID", name: "Lucid Motors", score: 90, doc_label: "LUCID_ESG_DATA", doc_hash: "", hash: "" }
];

// Export des données pour le registre
if (typeof module !== 'undefined') module.exports = { mobilityData };