const generateForensicHash = (name) => {
    // Simule un hash unique basé sur le nom de la marque pour le visuel
    let hash = "";
    const chars = "abcdef0123456789";
    for (let i = 0; i < 32; i++) {
        hash += chars.charAt(Math.floor(Math.random() * chars.length));
    }
    return "0x" + hash;
};

const registryData = [
    { name: "Hermès", score: 98 },
    { name: "Patek Philippe", score: 97 },
    { name: "Loro Piana", score: 96 },
    { name: "Brunello Cucinelli", score: 95 },
    { name: "Vacheron Constantin", score: 94 },
    { name: "Cartier", score: 94 },
    { name: "Rolex", score: 93 },
    { name: "Audemars Piguet", score: 93 },
    { name: "Chanel", score: 92 },
    { name: "Louis Vuitton", score: 91 },
    { name: "Van Cleef & Arpels", score: 91 },
    { name: "Schiaparelli", score: 91 },
    { name: "Piaget", score: 91 },
    { name: "Dior", score: 90 },
    { name: "Breguet", score: 90 },
    { name: "Comme des Garçons", score: 90 },
    { name: "Jaeger-LeCoultre", score: 89 },
    { name: "Dries Van Noten", score: 89 },
    { name: "Bulgari", score: 89 },
    { name: "Oscar de la Renta", score: 89 },
    { name: "IWC Schaffhausen", score: 88 },
    { name: "Omega", score: 88 },
    { name: "Maison Margiela", score: 88 },
    { name: "Thom Browne", score: 88 },
    { name: "Prada", score: 87 },
    { name: "Saint Laurent", score: 87 },
    { name: "Rick Owens", score: 87 },
    { name: "Chopard", score: 87 },
    { name: "Celine", score: 86 },
    { name: "Bottega Veneta", score: 86 },
    { name: "Sacai", score: 86 },
    { name: "Loewe", score: 85 },
    { name: "Stone Island", score: 85 },
    { name: "Lanvin", score: 85 },
    { name: "Montblanc", score: 85 },
    { name: "Gucci", score: 84 },
    { name: "Valentino", score: 84 },
    { name: "Ami Paris", score: 84 },
    { name: "Mugler", score: 84 },
    { name: "Reformation", score: 84 },
    { name: "Tiffany & Co.", score: 83 },
    { name: "Miu Miu", score: 83 },
    { name: "Marine Serre", score: 83 },
    { name: "Burberry", score: 82 },
    { name: "Fendi", score: 82 },
    { name: "Jacquemus", score: 82 },
    { name: "Chloé", score: 82 },
    { name: "Fear of God", score: 82 },
    { name: "Diane von Furstenberg", score: 82 },
    { name: "Max Mara", score: 81 },
    { name: "Zegna", score: 81 },
    { name: "JW Anderson", score: 81 },
    { name: "Coperni", score: 81 },
    { name: "Tag Heuer", score: 81 },
    { name: "The Row", score: 80 },
    { name: "Alaïa", score: 80 },
    { name: "Isabel Marant", score: 80 },
    { name: "Moncler Genius", score: 80 },
    { name: "Moncler", score: 79 },
    { name: "Alexander McQueen", score: 79 },
    { name: "Paco Rabanne", score: 79 },
    { name: "Givenchy", score: 78 },
    { name: "Balmain", score: 78 },
    { name: "Acne Studios", score: 78 },
    { name: "Hublot", score: 78 },
    { name: "Tom Ford", score: 77 },
    { name: "Salvatore Ferragamo", score: 77 },
    { name: "Paul Smith", score: 77 },
    { name: "Marc Jacobs", score: 77 },
    { name: "Etro", score: 76 },
    { name: "Missoni", score: 76 },
    { name: "Supreme", score: 76 },
    { name: "Ralph Lauren", score: 75 },
    { name: "Giorgio Armani", score: 75 },
    { name: "Zimmermann", score: 75 },
    { name: "Tory Burch", score: 74 },
    { name: "Kenzo", score: 74 },
    { name: "Coach", score: 73 },
    { name: "Michael Kors", score: 72 },
    { name: "Ganni", score: 72 },
    { name: "Longchamp", score: 71 },
    { name: "Bally", score: 70 },
    { name: "Tod’s", score: 70 },
    { name: "Swarovski", score: 70 },
    { name: "Jimmy Choo", score: 69 },
    { name: "Manolo Blahnik", score: 69 },
    { name: "Christian Louboutin", score: 68 },
    { name: "Skims", score: 68 },
    { name: "Hugo Boss", score: 67 },
    { name: "Dolce & Gabbana", score: 66 },
    { name: "Diesel", score: 66 },
    { name: "Versace", score: 65 },
    { name: "Vetements", score: 65 },
    { name: "Off-White", score: 64 },
    { name: "Roberto Cavalli", score: 64 },
    { name: "Moschino", score: 63 },
    { name: "Pandora", score: 62 },
    { name: "Dsquared2", score: 61 },
    { name: "Palm Angels", score: 59 },
    { name: "Balenciaga", score: 50 },
    { name: "Goyard", score: 46 },
    { name: "Philipp Plein", score: 42 }
].map(brand => ({
    ...brand,
    hash: generateForensicHash(brand.name)
}));