const registryData = [
    // --- TOP 100 LUXE & HERITAGE (RESTAURÉ) ---
    { name: "Patek Philippe", category: "Watchmaking", score: 98, hash: "0x2A_PAT_9800", moatDelta: "0.5%" },
    { name: "Hermès", category: "High-Value Leather", score: 96, hash: "0x2A_HER_9644", moatDelta: "1.2%" },
    { name: "Ferrari", category: "Automotive Heritage", score: 95, hash: "0x2A_FER_9588", moatDelta: "1.8%" },
    { name: "Rolex", category: "Watchmaking", score: 94, hash: "0x2A_ROL_9412", moatDelta: "2.1%" },
    { name: "Goyard", category: "Trunkmaking", score: 98, hash: "0x2A_GOY_9811", moatDelta: "0.4%" },
    { name: "Chanel", category: "Haute Couture", score: 92, hash: "0x2A_CHA_9233", moatDelta: "3.2%" },
    { name: "Brunello Cucinelli", category: "Quiet Luxury", score: 97, hash: "0x2A_BRU_9788", moatDelta: "0.9%" },
    { name: "Vacheron Constantin", category: "Watchmaking", score: 96, hash: "0x2A_VAC_9611", moatDelta: "1.1%" },
    { name: "LVMH Group", category: "Conglomerate", score: 89, hash: "0x2A_LVMH_8901", moatDelta: "4.5%" },
    { name: "Cartier", category: "Jewelry", score: 91, hash: "0x2A_CAR_9122", moatDelta: "2.9%" },
    { name: "Audemars Piguet", category: "Watchmaking", score: 93, hash: "0x2A_AUD_9344", moatDelta: "2.5%" },
    { name: "Dior", category: "Luxury Fashion", score: 87, hash: "0x2A_DIO_8701", moatDelta: "5.1%" },
    { name: "Breguet", category: "Watchmaking", score: 94, hash: "0x2A_BRE_9422", moatDelta: "1.9%" },
    { name: "Loewe", category: "Leather Goods", score: 88, hash: "0x2A_LOE_8833", moatDelta: "4.2%" },
    { name: "Prada", category: "Luxury Fashion", score: 85, hash: "0x2A_PRA_8544", moatDelta: "6.3%" },
    { name: "Bottega Veneta", category: "Luxury Fashion", score: 93, hash: "0x2A_BOT_9321", moatDelta: "2.2%" },
    { name: "Celine", category: "Luxury Fashion", score: 89, hash: "0x2A_CEL_8955", moatDelta: "3.8%" },
    { name: "Saint Laurent", category: "Luxury Fashion", score: 86, hash: "0x2A_YSL_8622", moatDelta: "5.4%" },
    { name: "Gucci", category: "Luxury Fashion", score: 82, hash: "0x2A_GUC_8211", moatDelta: "8.1%" },
    { name: "Balenciaga", category: "Luxury Fashion", score: 79, hash: "0x2A_BAL_7944", moatDelta: "12.2%" },
    { name: "A. Lange & Söhne", category: "Watchmaking", score: 97, hash: "0x2A_LAN_9711", moatDelta: "0.7%" },
    { name: "Richard Mille", category: "Watchmaking", score: 91, hash: "0x2A_RIC_9144", moatDelta: "3.5%" },
    { name: "Van Cleef & Arpels", category: "Jewelry", score: 95, hash: "0x2A_VCA_9522", moatDelta: "1.5%" },
    { name: "Berluti", category: "Shoemaking", score: 92, hash: "0x2A_BER_9233", moatDelta: "2.4%" },
    { name: "Rimowa", category: "Travel", score: 90, hash: "0x2A_RIM_9011", moatDelta: "3.1%" },
    { name: "Steinway & Sons", category: "Instruments", score: 98, hash: "0x2A_STE_9855", moatDelta: "0.3%" },
    { name: "Feadship", category: "Yachting", score: 96, hash: "0x2A_FEA_9622", moatDelta: "1.3%" },
    { name: "Riva", category: "Yachting", score: 94, hash: "0x2A_RIV_9411", moatDelta: "2.0%" },
    { name: "Bentley", category: "Automotive", score: 88, hash: "0x2A_BEN_8844", moatDelta: "4.8%" },
    { name: "Rolls-Royce", category: "Automotive", score: 95, hash: "0x2A_RR_9501", moatDelta: "1.6%" },
    { name: "Aston Martin", category: "Automotive", score: 84, hash: "0x2A_AST_8422", moatDelta: "7.1%" },
    { name: "Lamborghini", category: "Automotive", score: 86, hash: "0x2A_LAM_8633", moatDelta: "5.5%" },
    { name: "McLaren", category: "Automotive", score: 87, hash: "0x2A_MCL_8711", moatDelta: "4.9%" },
    { name: "Bugatti", category: "Automotive", score: 97, hash: "0x2A_BUG_9744", moatDelta: "0.6%" },
    { name: "Dom Pérignon", category: "Champagne", score: 93, hash: "0x2A_DOM_9322", moatDelta: "2.3%" },
    { name: "Krug", category: "Champagne", score: 95, hash: "0x2A_KRU_9511", moatDelta: "1.7%" },
    { name: "Louis Roederer", category: "Champagne", score: 94, hash: "0x2A_ROED_9433", moatDelta: "1.9%" },
    { name: "Macallan", category: "Spirits", score: 96, hash: "0x2A_MAC_9644", moatDelta: "1.1%" },
    { name: "Romanée-Conti", category: "Wine", score: 99, hash: "0x2A_DRC_9901", moatDelta: "0.1%" },
    { name: "Château Margaux", category: "Wine", score: 97, hash: "0x2A_MAR_9722", moatDelta: "0.8%" },
    { name: "Petrus", category: "Wine", score: 98, hash: "0x2A_PETR_9811", moatDelta: "0.4%" },
    { name: "Four Seasons", category: "Hospitality", score: 91, hash: "0x2A_FS_9144", moatDelta: "3.4%" },
    { name: "Aman Resorts", category: "Hospitality", score: 96, hash: "0x2A_AMA_9611", moatDelta: "1.2%" },
    { name: "Cheval Blanc", category: "Hospitality", score: 95, hash: "0x2A_CHE_9533", moatDelta: "1.8%" },
    { name: "Ritz-Carlton", category: "Hospitality", score: 89, hash: "0x2A_RITZ_8911", moatDelta: "4.2%" },
    { name: "Belmond", category: "Hospitality", score: 92, hash: "0x2A_BEL_9244", moatDelta: "2.5%" },
    { name: "NetJets", category: "Aviation", score: 90, hash: "0x2A_NET_9022", moatDelta: "3.9%" },
    { name: "VistaJet", category: "Aviation", score: 88, hash: "0x2A_VIS_8811", moatDelta: "4.5%" },
    { name: "Leica", category: "Photography", score: 96, hash: "0x2A_LEI_9655", moatDelta: "1.0%" },
    { name: "Hasselblad", category: "Photography", score: 94, hash: "0x2A_HAS_9433", moatDelta: "2.1%" },
    { name: "Bang & Olufsen", category: "Audio", score: 87, hash: "0x2A_BO_8722", moatDelta: "5.3%" },
    { name: "Technics", category: "Audio", score: 89, hash: "0x2A_TEC_8911", moatDelta: "3.8%" },
    { name: "Bowers & Wilkins", category: "Audio", score: 91, hash: "0x2A_BW_9144", moatDelta: "2.7%" },
    { name: "Davidoff", category: "Lifestyle", score: 90, hash: "0x2A_DAV_9011", moatDelta: "3.6%" },
    { name: "S.T. Dupont", category: "Lifestyle", score: 88, hash: "0x2A_DUP_8822", moatDelta: "4.4%" },
    { name: "Montblanc", category: "Writing Instruments", score: 89, hash: "0x2A_MON_8933", moatDelta: "3.2%" },
    { name: "Grafton", category: "Writing Instruments", score: 84, hash: "0x2A_GRA_8411", moatDelta: "6.5%" },
    { name: "Savile Row Co.", category: "Tailoring", score: 93, hash: "0x2A_SAV_9322", moatDelta: "2.4%" },
    { name: "Anderson & Sheppard", category: "Tailoring", score: 96, hash: "0x2A_AND_9611", moatDelta: "1.0%" },
    { name: "Charvet", category: "Tailoring", score: 97, hash: "0x2A_CHA_9744", moatDelta: "0.7%" },

    // --- AJOUTS RÉCENTS STRATÉGIQUES (IA, TECH, FINANCE) ---
    { name: "OpenAI", category: "AI Frontier", score: 82, hash: "0x2A_OPAI_8245", moatDelta: "8.4%" },
    { name: "NVIDIA", category: "Compute Infrastructure", score: 91, hash: "0x2A_NVDA_9102", moatDelta: "2.8%" },
    { name: "Anthropic", category: "AI Safety", score: 88, hash: "0x2A_ANTH_8811", moatDelta: "4.1%" },
    { name: "Apple", category: "Consumer Ecosystem", score: 93, hash: "0x2A_AAPL_9322", moatDelta: "2.3%" },
    { name: "Microsoft", category: "Enterprise Cloud", score: 87, hash: "0x2A_MSFT_8755", moatDelta: "5.2%" },
    { name: "Mistral AI", category: "Open Source AI", score: 85, hash: "0x2A_MIST_8544", moatDelta: "6.1%" },
    { name: "BlackRock", category: "Asset Management", score: 81, hash: "0x2A_BLK_8122", moatDelta: "9.2%" },
    { name: "Coinbase", category: "Digital Assets", score: 89, hash: "0x2A_COIN_8944", moatDelta: "3.7%" },
    { name: "Stripe", category: "Payment Infrastructure", score: 94, hash: "0x2A_STR_9488", moatDelta: "1.4%" },
    { name: "Goldman Sachs", category: "Investment Banking", score: 78, hash: "0x2A_GS_7833", moatDelta: "11.5%" },
    { name: "Revolut", category: "Neobanking", score: 84, hash: "0x2A_REV_8411", moatDelta: "7.3%" },
    { name: "Amazon", category: "Global Logistics", score: 76, hash: "0x2A_AMZ_7644", moatDelta: "14.2%" },
    { name: "Walmart", category: "Retail Operations", score: 79, hash: "0x2A_WMT_7922", moatDelta: "10.8%" },
    { name: "Tesla", category: "Sustainable Energy", score: 74, hash: "0x2A_TSLA_7411", moatDelta: "16.5%" },
    { name: "Patagonia", category: "Ethical Apparel", score: 97, hash: "0x2A_PATG_9722", moatDelta: "0.8%" },
    { name: "Zara (Inditex)", category: "Fast Fashion", score: 68, hash: "0x2A_ZARA_6844", moatDelta: "22.4%" },
    { name: "SpaceX", category: "Aerospace", score: 92, hash: "0x2A_SPX_9288", moatDelta: "3.1%" },
    { name: "Palantir", category: "Data Analytics", score: 86, hash: "0x2A_PLTR_8633", moatDelta: "5.9%" }
];